CREATE TABLE "gas_usage_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"technician_id" uuid NOT NULL,
	"technician_name" text NOT NULL,
	"client_name" text NOT NULL,
	"location" text DEFAULT '' NOT NULL,
	"planner_job_id" uuid,
	"job_type" text NOT NULL,
	"refrigerant_type" text NOT NULL,
	"refrigerant_class" text,
	"amount" numeric(10, 3) NOT NULL,
	"action_type" text NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"approved_supplier_id" text,
	"approved_supplier_name" text,
	"supplier_verified" boolean DEFAULT false,
	"pesepay_transaction_id" text,
	"odp" numeric(5, 2),
	"gwp" numeric(8, 2),
	"co2_eq_emissions" numeric(12, 3),
	"ashrae_safety_class" text,
	"supplier_id" text,
	"purchase_transaction_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
