import { EquipmentRecord, PredictiveAlert } from '@/types/index';

export const MOCK_EQUIPMENT_RECORDS: EquipmentRecord[] = [
  {
    id: 'eq-001',
    equipmentId: 'EQ-HTR-001',
    clientName: 'Meikles Hotel',
    province: 'Harare',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2026-01-15',
    nextServiceDue: '2026-04-15',
    status: 'due-soon',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-1', date: '2026-01-15', notes: 'Quarterly maintenance completed', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
    predictedFailureReason: 'Compressor vibration rising above baseline.',
    recommendedAction: 'Schedule service before peak occupancy weekend.',
  },
  {
    id: 'eq-002',
    equipmentId: 'EQ-SPR-002',
    clientName: 'Spar Bulawayo',
    province: 'Bulawayo',
    refrigerantType: 'R-744',
    ashraeSafetyClass: 'A1',
    lastServiceDate: '2026-01-28',
    nextServiceDue: '2026-04-28',
    status: 'normal',
    technicianName: 'Nyasha Chikomo',
    serviceHistory: [
      { id: 'srv-2', date: '2026-01-28', notes: 'Temperature calibration performed', technicianName: 'Nyasha Chikomo', status: 'completed' },
    ],
  },
  {
    id: 'eq-003',
    equipmentId: 'EQ-DEL-003',
    clientName: 'Delta Beverages',
    province: 'Harare',
    refrigerantType: 'R-32',
    ashraeSafetyClass: 'A2L',
    lastServiceDate: '2025-12-20',
    nextServiceDue: '2026-03-20',
    status: 'overdue',
    technicianName: 'Munyaradzi Dube',
    serviceHistory: [
      { id: 'srv-3', date: '2025-12-20', notes: 'Leak test and recharge completed', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
    predictedFailureReason: 'Evaporator coil frosting and reduced airflow.',
    recommendedAction: 'Create urgent service job and inspect airflow path.',
  },
  {
    id: 'eq-004',
    equipmentId: 'EQ-OKZ-004',
    clientName: 'Ok Zimbabwe - Harare',
    province: 'Harare',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2026-02-03',
    nextServiceDue: '2026-05-03',
    status: 'normal',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-4', date: '2026-02-03', notes: 'Cabinet seals replaced', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
  },
  {
    id: 'eq-005',
    equipmentId: 'EQ-MUZ-005',
    clientName: 'Mutare Motors',
    province: 'Manicaland',
    refrigerantType: 'R-32',
    ashraeSafetyClass: 'A2L',
    lastServiceDate: '2026-02-10',
    nextServiceDue: '2026-05-10',
    status: 'due-soon',
    technicianName: 'Munyaradzi Dube',
    serviceHistory: [
      { id: 'srv-5', date: '2026-02-10', notes: 'Thermostat recalibration', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
    predictedFailureReason: 'Supply fan current trending upward.',
    recommendedAction: 'Inspect motor bearings and schedule load test.',
  },
  {
    id: 'eq-006',
    equipmentId: 'EQ-GWE-006',
    clientName: 'Gweru Fresh Foods',
    province: 'Midlands',
    refrigerantType: 'R-744',
    ashraeSafetyClass: 'A1',
    lastServiceDate: '2025-11-30',
    nextServiceDue: '2026-02-28',
    status: 'overdue',
    technicianName: 'Nyasha Chikomo',
    serviceHistory: [
      { id: 'srv-6', date: '2025-11-30', notes: 'Pressure sensor replaced', technicianName: 'Nyasha Chikomo', status: 'completed' },
    ],
    predictedFailureReason: 'Pressure instability observed in trend logs.',
    recommendedAction: 'Dispatch technician and capture differential pressure readings.',
  },
  {
    id: 'eq-007',
    equipmentId: 'EQ-KWE-007',
    clientName: 'Kwekwe Cold Stores',
    province: 'Midlands',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2026-01-18',
    nextServiceDue: '2026-04-18',
    status: 'normal',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-7', date: '2026-01-18', notes: 'Routine service and leak check', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
  },
  {
    id: 'eq-008',
    equipmentId: 'EQ-BYO-008',
    clientName: 'Bulawayo Logistics Hub',
    province: 'Bulawayo',
    refrigerantType: 'R-22',
    ashraeSafetyClass: 'A1',
    lastServiceDate: '2026-02-14',
    nextServiceDue: '2026-05-14',
    status: 'due-soon',
    technicianName: 'Nyasha Chikomo',
    serviceHistory: [
      { id: 'srv-8', date: '2026-02-14', notes: 'Legacy asset inspection', technicianName: 'Nyasha Chikomo', status: 'completed' },
    ],
    predictedFailureReason: 'Aged compressor with frequent short cycling.',
    recommendedAction: 'Plan replacement assessment and monitor amp draw.',
  },
  {
    id: 'eq-009',
    equipmentId: 'EQ-MUT-009',
    clientName: 'Mutare Supermarket',
    province: 'Manicaland',
    refrigerantType: 'R-32',
    ashraeSafetyClass: 'A2L',
    lastServiceDate: '2026-01-09',
    nextServiceDue: '2026-04-09',
    status: 'normal',
    technicianName: 'Munyaradzi Dube',
    serviceHistory: [
      { id: 'srv-9', date: '2026-01-09', notes: 'Condensate drain cleared', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
  },
  {
    id: 'eq-010',
    equipmentId: 'EQ-MAS-010',
    clientName: 'Masvingo Retail Park',
    province: 'Masvingo',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2026-01-05',
    nextServiceDue: '2026-04-05',
    status: 'overdue',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-10', date: '2026-01-05', notes: 'Leak repair and recovery', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
    predictedFailureReason: 'Pressure loss in discharge line.',
    recommendedAction: 'Create corrective maintenance job immediately.',
  },
  {
    id: 'eq-011',
    equipmentId: 'EQ-GWT-011',
    clientName: 'Gwanda Agro Warehouse',
    province: 'Matabeleland South',
    refrigerantType: 'R-744',
    ashraeSafetyClass: 'A1',
    lastServiceDate: '2026-02-01',
    nextServiceDue: '2026-05-01',
    status: 'normal',
    technicianName: 'Nyasha Chikomo',
    serviceHistory: [
      { id: 'srv-11', date: '2026-02-01', notes: 'Service completed without defects', technicianName: 'Nyasha Chikomo', status: 'completed' },
    ],
  },
  {
    id: 'eq-012',
    equipmentId: 'EQ-HWN-012',
    clientName: 'Hwange Fuel Mart',
    province: 'Matabeleland North',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2026-01-12',
    nextServiceDue: '2026-04-12',
    status: 'due-soon',
    technicianName: 'Munyaradzi Dube',
    serviceHistory: [
      { id: 'srv-12', date: '2026-01-12', notes: 'Insulation inspection', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
    predictedFailureReason: 'High compressor run-time during peak hours.',
    recommendedAction: 'Review setpoints and confirm door seal integrity.',
  },
  {
    id: 'eq-013',
    equipmentId: 'EQ-CHI-013',
    clientName: 'Chinhoyi Distribution Centre',
    province: 'Mashonaland West',
    refrigerantType: 'R-32',
    ashraeSafetyClass: 'A2L',
    lastServiceDate: '2026-02-17',
    nextServiceDue: '2026-05-17',
    status: 'normal',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-13', date: '2026-02-17', notes: 'Controls calibration and cleaning', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
  },
  {
    id: 'eq-014',
    equipmentId: 'EQ-BIN-014',
    clientName: 'Bindura Dairy',
    province: 'Mashonaland Central',
    refrigerantType: 'R-744',
    ashraeSafetyClass: 'A1',
    lastServiceDate: '2026-01-25',
    nextServiceDue: '2026-04-25',
    status: 'due-soon',
    technicianName: 'Nyasha Chikomo',
    serviceHistory: [
      { id: 'srv-14', date: '2026-01-25', notes: 'Filter drier replacement', technicianName: 'Nyasha Chikomo', status: 'completed' },
    ],
    predictedFailureReason: 'Slight rise in discharge pressure over 3 cycles.',
    recommendedAction: 'Add monitoring job and verify refrigerant charge.',
  },
  {
    id: 'eq-015',
    equipmentId: 'EQ-MAR-015',
    clientName: 'Marondera Food Hub',
    province: 'Mashonaland East',
    refrigerantType: 'R-290',
    ashraeSafetyClass: 'A3',
    lastServiceDate: '2025-12-29',
    nextServiceDue: '2026-03-29',
    status: 'overdue',
    technicianName: 'Munyaradzi Dube',
    serviceHistory: [
      { id: 'srv-15', date: '2025-12-29', notes: 'Evaporator clean-up', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
    predictedFailureReason: 'Icing around the evaporator housing.',
    recommendedAction: 'Create urgent service job and inspect defrost cycle.',
  },
  {
    id: 'eq-016',
    equipmentId: 'EQ-MUZ-016',
    clientName: 'Mutare Clinic',
    province: 'Manicaland',
    refrigerantType: 'R-32',
    ashraeSafetyClass: 'A2L',
    lastServiceDate: '2026-02-20',
    nextServiceDue: '2026-05-20',
    status: 'normal',
    technicianName: 'Tapiwa Moyo',
    serviceHistory: [
      { id: 'srv-16', date: '2026-02-20', notes: 'Temperature trend validated', technicianName: 'Tapiwa Moyo', status: 'completed' },
    ],
  },
];

export const MOCK_PREDICTIVE_ALERTS: PredictiveAlert[] = [
  {
    id: 'alert-001',
    equipmentId: 'EQ-DEL-003',
    clientName: 'Delta Beverages',
    province: 'Harare',
    predictedFailureReason: 'Evaporator coil frosting and reduced airflow.',
    recommendedAction: 'Dispatch service job and check airflow path.',
    urgency: 'high',
    status: 'overdue',
  },
  {
    id: 'alert-002',
    equipmentId: 'EQ-GWE-006',
    clientName: 'Gweru Fresh Foods',
    province: 'Midlands',
    predictedFailureReason: 'Pressure instability observed in trend logs.',
    recommendedAction: 'Verify sensors and capture pressure readings.',
    urgency: 'high',
    status: 'overdue',
  },
  {
    id: 'alert-003',
    equipmentId: 'EQ-BYO-008',
    clientName: 'Bulawayo Logistics Hub',
    province: 'Bulawayo',
    predictedFailureReason: 'Aged compressor with frequent short cycling.',
    recommendedAction: 'Plan replacement assessment and monitor amp draw.',
    urgency: 'medium',
    status: 'due-soon',
  },
  {
    id: 'alert-004',
    equipmentId: 'EQ-MAS-010',
    clientName: 'Masvingo Retail Park',
    province: 'Masvingo',
    predictedFailureReason: 'Pressure loss in discharge line.',
    recommendedAction: 'Create corrective maintenance job immediately.',
    urgency: 'high',
    status: 'overdue',
  },
];
