import { PlannerClient, PlannerJob, PlannerSafetyChecklistItem } from '@/types/index';

export const MOCK_PLANNER_SAFETY_CHECKLIST: PlannerSafetyChecklistItem[] = [
  { id: 'pcl-1', label: 'PPE confirmed', required: true, completed: true, appliesTo: 'all' },
  { id: 'pcl-2', label: 'Ventilation verified', required: true, completed: true, appliesTo: ['A2L', 'A3'] },
  { id: 'pcl-3', label: 'Ignition sources isolated', required: true, completed: false, appliesTo: ['A2L', 'A3'] },
  { id: 'pcl-4', label: 'Leak detector available', required: true, completed: true, appliesTo: 'all' },
  { id: 'pcl-5', label: 'Pre-job briefing signed', required: true, completed: true, appliesTo: 'all' },
];

export const MOCK_PLANNER_CLIENTS: PlannerClient[] = [
  {
    id: 'client-1',
    name: 'Meikles Hotel',
    location: '3 Jason Moyo Ave, Harare',
    province: 'Harare',
    contactPerson: 'Tariro Murehwa',
    contactNumber: '+263 77 401 2201',
    serviceHistory: [
      { id: 'srv-1', date: '2026-01-15', notes: 'VRF leak repair and re-commissioning', technicianName: 'Tapiwa Moyo', status: 'completed' },
      { id: 'srv-2', date: '2026-02-11', notes: 'Quarterly cold room inspection', technicianName: 'Munyaradzi Dube', status: 'completed' },
    ],
  },
  {
    id: 'client-2',
    name: 'Pick n Pay Highlands',
    location: 'Enterprise Road, Harare',
    province: 'Harare',
    contactPerson: 'Rudo Chikosha',
    contactNumber: '+263 78 201 4403',
    serviceHistory: [
      { id: 'srv-3', date: '2026-02-02', notes: 'CO2 rack compressor service', technicianName: 'Tapiwa Moyo', status: 'in-progress' },
    ],
  },
  {
    id: 'client-3',
    name: 'Spar Bulawayo',
    location: 'Fife Street, Bulawayo',
    province: 'Bulawayo',
    contactPerson: 'Blessing Ncube',
    contactNumber: '+263 71 612 7740',
    serviceHistory: [
      { id: 'srv-4', date: '2026-01-28', notes: 'Display case temperature calibration', technicianName: 'Nyasha Chikomo', status: 'completed' },
      { id: 'srv-5', date: '2026-02-19', notes: 'Scheduled follow-up for door seal inspection', technicianName: 'Nyasha Chikomo', status: 'follow-up' },
    ],
  },
  {
    id: 'client-4',
    name: 'Delta Beverages',
    location: 'Southerton Industrial Area, Harare',
    province: 'Harare',
    contactPerson: 'Farai Gondo',
    contactNumber: '+263 77 301 9912',
    serviceHistory: [
      { id: 'srv-6', date: '2026-02-22', notes: 'Industrial chiller diagnostics', technicianName: 'Munyaradzi Dube', status: 'in-progress' },
    ],
  },
];

export const MOCK_PLANNER_JOBS: PlannerJob[] = [
  {
    id: 'plan-001',
    clientId: 'client-1',
    clientName: 'Meikles Hotel',
    location: '3 Jason Moyo Ave, Harare',
    province: 'Harare',
    district: 'Harare Central',
    technicianId: '1',
    technicianName: 'Tapiwa Moyo',
    jobType: 'COLD_ROOM',
    refrigerantClass: 'A1',
    scheduledDate: '2026-03-31',
    status: 'scheduled',
    preJobChecklistComplete: true,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    notes: 'Routine preventive maintenance for ballroom refrigeration plant.',
    createdAt: '2026-03-20T08:30:00.000Z',
    updatedAt: '2026-03-29T15:10:00.000Z',
  },
  {
    id: 'plan-002',
    clientId: 'client-2',
    clientName: 'Pick n Pay Highlands',
    location: 'Enterprise Road, Harare',
    province: 'Harare',
    district: 'Harare North',
    technicianId: '1',
    technicianName: 'Tapiwa Moyo',
    jobType: 'FREEZER_ROOM',
    refrigerantClass: 'A2L',
    scheduledDate: '2026-03-31',
    status: 'in-progress',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    notes: 'A2L installation requires mandatory ignition-source check.',
    createdAt: '2026-03-18T10:00:00.000Z',
    updatedAt: '2026-03-31T09:45:00.000Z',
  },
  {
    id: 'plan-003',
    clientId: 'client-3',
    clientName: 'Spar Bulawayo',
    location: 'Fife Street, Bulawayo',
    province: 'Bulawayo',
    district: 'Bulawayo South',
    technicianId: '2',
    technicianName: 'Nyasha Chikomo',
    jobType: 'C90_FREEZER',
    refrigerantClass: 'A1',
    scheduledDate: '2026-04-01',
    status: 'completed',
    preJobChecklistComplete: true,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item, completed: true })),
    notes: 'Door seal replacement and recovery log updated.',
    createdAt: '2026-03-15T11:20:00.000Z',
    updatedAt: '2026-03-30T16:00:00.000Z',
  },
  {
    id: 'plan-004',
    clientId: 'client-4',
    clientName: 'Delta Beverages',
    location: 'Southerton Industrial Area, Harare',
    province: 'Harare',
    district: 'Harare South',
    technicianId: '3',
    technicianName: 'Munyaradzi Dube',
    jobType: 'C60_FREEZER',
    refrigerantClass: 'A3',
    scheduledDate: '2026-04-02',
    status: 'follow-up',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    notes: 'Follow-up after pressure test variance.',
    createdAt: '2026-03-10T07:10:00.000Z',
    updatedAt: '2026-03-30T08:30:00.000Z',
  },
  {
    id: 'plan-005',
    clientId: 'client-1',
    clientName: 'Meikles Hotel',
    location: '3 Jason Moyo Ave, Harare',
    province: 'Harare',
    district: 'Harare Central',
    technicianId: '2',
    technicianName: 'Nyasha Chikomo',
    jobType: 'COLD_ROOM',
    refrigerantClass: 'A1',
    scheduledDate: '2026-04-03',
    status: 'scheduled',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    createdAt: '2026-03-21T14:05:00.000Z',
    updatedAt: '2026-03-30T11:00:00.000Z',
  },
  {
    id: 'plan-006',
    clientId: 'client-2',
    clientName: 'Pick n Pay Highlands',
    location: 'Enterprise Road, Harare',
    province: 'Harare',
    district: 'Harare North',
    technicianId: '3',
    technicianName: 'Munyaradzi Dube',
    jobType: 'C40_FREEZER',
    refrigerantClass: 'A2L',
    scheduledDate: '2026-04-04',
    status: 'scheduled',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    notes: 'Client requested early morning site access.',
    createdAt: '2026-03-22T08:45:00.000Z',
    updatedAt: '2026-03-30T13:40:00.000Z',
  },
  {
    id: 'plan-007',
    clientId: 'client-3',
    clientName: 'Spar Bulawayo',
    location: 'Fife Street, Bulawayo',
    province: 'Bulawayo',
    district: 'Bulawayo South',
    technicianId: '1',
    technicianName: 'Tapiwa Moyo',
    jobType: 'FREEZER_ROOM',
    refrigerantClass: 'A1',
    scheduledDate: '2026-04-05',
    status: 'scheduled',
    preJobChecklistComplete: true,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    createdAt: '2026-03-25T09:10:00.000Z',
    updatedAt: '2026-03-30T09:05:00.000Z',
  },
  {
    id: 'plan-008',
    clientId: 'client-4',
    clientName: 'Delta Beverages',
    location: 'Southerton Industrial Area, Harare',
    province: 'Harare',
    district: 'Harare South',
    technicianId: '2',
    technicianName: 'Nyasha Chikomo',
    jobType: 'C90_FREEZER',
    refrigerantClass: 'A3',
    scheduledDate: '2026-04-06',
    status: 'in-progress',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    notes: 'A3 gate requires PPE confirmation before compressor start.',
    createdAt: '2026-03-24T12:00:00.000Z',
    updatedAt: '2026-03-31T07:30:00.000Z',
  },
  {
    id: 'plan-009',
    clientId: 'client-1',
    clientName: 'Meikles Hotel',
    location: '3 Jason Moyo Ave, Harare',
    province: 'Harare',
    district: 'Harare Central',
    technicianId: '3',
    technicianName: 'Munyaradzi Dube',
    jobType: 'C60_FREEZER',
    refrigerantClass: 'A1',
    scheduledDate: '2026-04-07',
    status: 'follow-up',
    preJobChecklistComplete: true,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item, completed: true })),
    notes: 'Return visit for post-commissioning adjustment.',
    createdAt: '2026-03-26T08:20:00.000Z',
    updatedAt: '2026-03-31T06:50:00.000Z',
  },
  {
    id: 'plan-010',
    clientId: 'client-4',
    clientName: 'Delta Beverages',
    location: 'Southerton Industrial Area, Harare',
    province: 'Harare',
    district: 'Harare South',
    technicianId: '1',
    technicianName: 'Tapiwa Moyo',
    jobType: 'COLD_ROOM',
    refrigerantClass: 'A1',
    scheduledDate: '2026-04-08',
    status: 'scheduled',
    preJobChecklistComplete: false,
    checklistItems: MOCK_PLANNER_SAFETY_CHECKLIST.map(item => ({ ...item })),
    createdAt: '2026-03-27T15:15:00.000Z',
    updatedAt: '2026-03-31T10:10:00.000Z',
  },
];
