import type { TrainerCertificateRequest, TrainingSession } from '@/types/index';

export const MOCK_TRAINING_SESSIONS: TrainingSession[] = [
  {
    id: 'training-001',
    title: 'Low GWP Refrigerants Safety Bootcamp',
    summary: 'Three-day practical and theory workshop covering safe low-GWP handling, leak response, and documentation.',
    venue: 'HEVACRAZ Harare Training Centre',
    province: 'Harare',
    startDate: '2026-04-18T08:30:00.000Z',
    endDate: '2026-04-20T16:30:00.000Z',
    feeUsd: 120,
    seats: 24,
    seatsRemaining: 9,
    trainerName: 'Tendai Moyo',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-002',
    title: 'Transcritical CO2 Systems Intensive',
    summary: 'Advanced training on controls, commissioning, and fault finding for R-744 systems.',
    venue: 'Bulawayo Polytechnic Lab B',
    province: 'Bulawayo',
    startDate: '2026-04-24T09:00:00.000Z',
    endDate: '2026-04-25T15:30:00.000Z',
    feeUsd: 180,
    seats: 18,
    seatsRemaining: 4,
    trainerName: 'Chenai Sibanda',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-003',
    title: 'Hydrocarbon Service Practice Clinic',
    summary: 'Field-safe R-290 and R-600a procedures for service teams and workshop supervisors.',
    venue: 'Mutare Technical Hall',
    province: 'Manicaland',
    startDate: '2026-05-02T08:00:00.000Z',
    endDate: '2026-05-02T17:00:00.000Z',
    feeUsd: 90,
    seats: 20,
    seatsRemaining: 12,
    trainerName: 'Farai Kanyuchi',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-004',
    title: 'COC Issuance & Record-Keeping Workshop',
    summary: 'One-day hands-on for technicians preparing to issue Certificates of Conformity. Covers platform workflow, evidence capture, and audit-proof documentation.',
    venue: 'HEVACRAZ Harare Training Centre',
    province: 'Harare',
    startDate: '2026-05-09T09:00:00.000Z',
    endDate: '2026-05-09T16:00:00.000Z',
    feeUsd: 60,
    seats: 30,
    seatsRemaining: 18,
    trainerName: 'Tendai Moyo',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-005',
    title: 'Ammonia (R-717) Industrial Safety',
    summary: 'Two-day induction for technicians servicing industrial ammonia refrigeration plant. PPE, leak protocol, and regulatory overview.',
    venue: 'Kadoma Industrial Training Centre',
    province: 'Mashonaland West',
    startDate: '2026-05-15T08:00:00.000Z',
    endDate: '2026-05-16T16:00:00.000Z',
    feeUsd: 150,
    seats: 16,
    seatsRemaining: 11,
    trainerName: 'Farai Kanyuchi',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-006',
    title: 'Refrigerant Recovery & Reclaim Certification',
    summary: 'Certification exam prep for recovery technicians. Covers equipment handling, cylinder protocol, and reporting to the NOU.',
    venue: 'HEVACRAZ Harare Training Centre',
    province: 'Harare',
    startDate: '2026-05-22T09:00:00.000Z',
    endDate: '2026-05-23T16:00:00.000Z',
    feeUsd: 140,
    seats: 20,
    seatsRemaining: 7,
    trainerName: 'Chenai Sibanda',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-007',
    title: 'Heat Pump Sizing & Commissioning',
    summary: 'Residential and light-commercial heat pump design. Load calculation, refrigerant selection, and commissioning checklists.',
    venue: 'Gweru Midlands Hotel',
    province: 'Midlands',
    startDate: '2026-06-06T09:00:00.000Z',
    endDate: '2026-06-07T16:30:00.000Z',
    feeUsd: 130,
    seats: 22,
    seatsRemaining: 22,
    trainerName: 'Tendai Moyo',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-008',
    title: 'Cold Room Design Masterclass',
    summary: 'Commercial cold room sizing, panel spec, and compliance walkthrough. Includes site visit to a working cold-chain facility.',
    venue: 'Masvingo Technical College',
    province: 'Masvingo',
    startDate: '2026-06-13T08:30:00.000Z',
    endDate: '2026-06-14T16:30:00.000Z',
    feeUsd: 160,
    seats: 18,
    seatsRemaining: 14,
    trainerName: 'Farai Kanyuchi',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
  {
    id: 'training-009',
    title: 'Apprentice Fundamentals (Student Track)',
    summary: 'Free three-day session for Polytechnic students on HVAC-R basics, safety culture, and career pathways. Student plan required.',
    venue: 'Harare Polytechnic',
    province: 'Harare',
    startDate: '2026-06-20T09:00:00.000Z',
    endDate: '2026-06-22T15:00:00.000Z',
    feeUsd: 0,
    seats: 40,
    seatsRemaining: 27,
    trainerName: 'Chenai Sibanda',
    trainerEmail: 'trainer@coolpro.demo',
    status: 'open',
  },
];

export const MOCK_TRAINER_CERTIFICATE_REQUESTS: TrainerCertificateRequest[] = [
  {
    id: 'trainer-cert-001',
    technicianId: '1',
    technicianName: 'Tapiwa Moyo',
    technicianRegistrationNumber: 'ZIM/TECH/2023/001',
    technicianCompany: 'Cooling Systems Zimbabwe',
    trainerName: 'Demo Trainer',
    trainerEmail: 'trainer@coolpro.demo',
    courseTitle: 'Low GWP Refrigerants Safety',
    examDate: '2026-03-20',
    theoryScore: 82,
    practicalScore: 88,
    overallScore: 85,
    notes: 'Strong handling discipline and safe charging procedure.',
    status: 'submitted-for-admin-approval',
    submittedAt: '2026-03-21T10:00:00.000Z',
  },
  {
    id: 'trainer-cert-002',
    technicianId: '2',
    technicianName: 'Nyasha Chikomo',
    technicianRegistrationNumber: 'ZIM/TECH/2023/002',
    technicianCompany: 'Chikomo Cooling Services',
    trainerName: 'Demo Trainer',
    trainerEmail: 'trainer@coolpro.demo',
    courseTitle: 'R-744 (CO2) System Specialist',
    examDate: '2026-03-18',
    theoryScore: 90,
    practicalScore: 93,
    overallScore: 92,
    notes: 'Approved for certification pending trainer issuance.',
    status: 'admin-approved',
    submittedAt: '2026-03-19T09:15:00.000Z',
    reviewedAt: '2026-03-22T14:30:00.000Z',
    adminReviewer: 'Demo Program Admin',
  },
];
