import type { SupplierLedgerEntry } from '@/types/index';

export const DEMO_VENDOR_EMAIL = 'vendor@coolpro.demo';

export const MOCK_VENDOR_LEDGER: SupplierLedgerEntry[] = [
  {
    id: 'ledger-001',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'purchase',
    counterpartyName: 'Zimbabwe Refrigeration Supplies',
    counterpartyType: 'importer',
    province: 'Harare',
    refrigerant: 'R-290',
    quantityKg: 240,
    unitPriceUsd: 18.5,
    totalValueUsd: 4440,
    invoiceNumber: 'INV-260301',
    transactionDate: '2026-03-01T09:20:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: true,
    notes: 'March opening stock replenishment.',
  },
  {
    id: 'ledger-002',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'Eastern Cold Chain Logistics',
    counterpartyType: 'cold-chain-client',
    province: 'Manicaland',
    refrigerant: 'R-290',
    quantityKg: 58,
    unitPriceUsd: 26,
    totalValueUsd: 1508,
    invoiceNumber: 'SL-260304',
    transactionDate: '2026-03-04T12:40:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: true,
    notes: 'Quarterly delivery to depot.',
  },
  {
    id: 'ledger-003',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'Nyanga Fresh Produce',
    counterpartyType: 'retailer',
    province: 'Manicaland',
    refrigerant: 'R-32',
    quantityKg: 36,
    unitPriceUsd: 29,
    totalValueUsd: 1044,
    invoiceNumber: 'SL-260309',
    transactionDate: '2026-03-09T10:15:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: false,
    clientReported: true,
    notes: 'Pending NOU filing batch.',
  },
  {
    id: 'ledger-004',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'purchase',
    counterpartyName: 'CoolTech Zimbabwe',
    counterpartyType: 'distributor',
    province: 'Bulawayo',
    refrigerant: 'R-32',
    quantityKg: 180,
    unitPriceUsd: 21,
    totalValueUsd: 3780,
    invoiceNumber: 'INV-260311',
    transactionDate: '2026-03-11T08:55:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: true,
    notes: 'Supplementary stock for retail branch orders.',
  },
  {
    id: 'ledger-005',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'Mutare Central Hospital',
    counterpartyType: 'contractor',
    province: 'Manicaland',
    refrigerant: 'R-744',
    quantityKg: 42,
    unitPriceUsd: 31,
    totalValueUsd: 1302,
    invoiceNumber: 'SL-260315',
    transactionDate: '2026-03-15T15:05:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: false,
    notes: 'Client delivery note awaiting confirmation.',
  },
  {
    id: 'ledger-006',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'Spar Mutare',
    counterpartyType: 'retailer',
    province: 'Manicaland',
    refrigerant: 'R-290',
    quantityKg: 64,
    unitPriceUsd: 27,
    totalValueUsd: 1728,
    invoiceNumber: 'SL-260319',
    transactionDate: '2026-03-19T14:30:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: false,
    clientReported: true,
    notes: 'Queued for end-of-month NOU declaration.',
  },
  {
    id: 'ledger-007',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'purchase',
    counterpartyName: 'African HVAC Distributors',
    counterpartyType: 'importer',
    province: 'Midlands',
    refrigerant: 'R-744',
    quantityKg: 120,
    unitPriceUsd: 23,
    totalValueUsd: 2760,
    invoiceNumber: 'INV-260321',
    transactionDate: '2026-03-21T11:10:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: true,
    notes: 'CO2 cylinder refill batch.',
  },
  {
    id: 'ledger-008',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'PrimeCool Services',
    counterpartyType: 'technician',
    province: 'Manicaland',
    refrigerant: 'R-32',
    quantityKg: 28,
    unitPriceUsd: 30,
    totalValueUsd: 840,
    invoiceNumber: 'SL-260324',
    transactionDate: '2026-03-24T09:45:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: true,
    clientReported: true,
    notes: 'Service partner top-up stock.',
  },
  {
    id: 'ledger-009',
    supplierEmail: DEMO_VENDOR_EMAIL,
    supplierName: 'Mutare Cooling Gas Traders',
    direction: 'sale',
    counterpartyName: 'GreenFoods Distribution',
    counterpartyType: 'cold-chain-client',
    province: 'Masvingo',
    refrigerant: 'R-290',
    quantityKg: 33,
    unitPriceUsd: 28,
    totalValueUsd: 924,
    invoiceNumber: 'SL-260327',
    transactionDate: '2026-03-27T16:20:00.000Z',
    referenceMonth: '2026-03',
    reportedToNou: false,
    clientReported: false,
    notes: 'Awaiting client sign-off and filing.',
  },
];
